DELETE http://localhost:3003/api/blogs/65ac91d98c0cd52d58650826
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1YWM3YjE2MTVlYTA3YWEyZjQzMWQzNSIsImlhdCI6MTcwNTgwOTQ5OH0.YNnZRO4CSt-kgT9BNxMjhlB_X8JE0WfxWp95yLSkIlA